name: Security Checks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1" # Mondays

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-deny
          key: cargo-deny-bin-v0
      - name: Install cargo-deny
        run: |
          if ! command -v cargo-deny >/dev/null; then
            cargo install cargo-deny --locked
          fi
      - name: Run cargo-deny
        run: cargo-deny check
